apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jeffrey-server.fullname" . }}
  labels:
    {{- include "jeffrey-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "jeffrey-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "jeffrey-server.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "jeffrey-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.grpcPort }}
              protocol: TCP
          env:
            - name: SPRING_CONFIG_LOCATION
              value: /jeffrey/application.properties
            - name: JEFFREY_HOME
              value: {{ .Values.sharedVolume.mountPath | quote }}
            {{- if not .Values.selfProfile.enabled }}
            - name: JEFFREY_ENABLED
              value: "false"
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-config
              mountPath: /jeffrey
              readOnly: true
            - name: jeffrey-shared
              mountPath: {{ .Values.sharedVolume.mountPath }}
      volumes:
        - name: app-config
          configMap:
            name: {{ include "jeffrey-server.fullname" . }}-config
        - name: jeffrey-shared
          persistentVolumeClaim:
            claimName: {{ .Values.sharedVolume.claimName }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
