{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jeffrey-server.fullname" . }}
  labels:
    {{- include "jeffrey-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "jeffrey-server.fullname" $ }}
                port:
                  number: {{ $.Values.service.httpPort }}
          {{- end }}
    {{- end }}
{{- end }}
{{- if .Values.grpcIngress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jeffrey-server.fullname" . }}-grpc
  labels:
    {{- include "jeffrey-server.labels" . | nindent 4 }}
  {{- with .Values.grpcIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.grpcIngress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.grpcIngress.tls }}
  tls:
    {{- range .Values.grpcIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.grpcIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "jeffrey-server.fullname" $ }}
                port:
                  number: {{ $.Values.service.grpcPort }}
          {{- end }}
    {{- end }}
{{- end }}
