version: "3.9"
services:
  app_all:
    container_name: app
    image: jfr-test
    volumes:
      - /tmp/asyncprofiler:/tmp/asyncprofiler
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - seccomp:unconfined
    cpu_quota: 100000
    mem_limit: 500m
    memswap_limit: 500m
    network_mode: host
    environment:
      - JDK_JAVA_OPTIONS=-Xmx100m -Xms100m -Xmn50m -XX:+UseSerialGC -XX:+AlwaysPreTouch -XX:MaxTenuringThreshold=0 -DcacheSize=10000 -Dreactor.netty.ioWorkerCount=1 -Dreactor.netty.http.server.accessLogEnabled=true -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints -Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=localhost

  app_jfr:
    container_name: app
    image: jfr-test
    volumes:
      - /tmp/asyncprofiler:/tmp/asyncprofiler
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - seccomp:unconfined
    cpu_quota: 100000
    mem_limit: 500m
    memswap_limit: 500m
    network_mode: host
    environment:
      - JDK_JAVA_OPTIONS=-Xmx200m -Xms200m -Xmn100m -XX:+UseSerialGC -XX:StartFlightRecording=filename=/tmp/asyncprofiler,settings=/app/resources/custom.jfc,dumponexit=true -Dreactor.netty.ioWorkerCount=1 -Dreactor.netty.http.server.accessLogEnabled=true

  app_measure_gc:
    container_name: app
    image: jfr-test
    volumes:
      - /tmp/asyncprofiler:/tmp/asyncprofiler
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - seccomp:unconfined
    cpu_quota: 100000
    mem_limit: 500m
    memswap_limit: 500m
    network_mode: host
    environment:
      - JDK_JAVA_OPTIONS=-Xmx100m -Xms100m -Xmn50m -XX:+UseSerialGC -XX:+AlwaysPreTouch -XX:MaxTenuringThreshold=0 -DcacheSize=10000 -XX:StartFlightRecording=filename=/tmp/asyncprofiler,settings=/app/resources/custom.jfc,dumponexit=true -Dreactor.netty.ioWorkerCount=1 -Dreactor.netty.http.server.accessLogEnabled=true
