FROM petrbouda/temurin-asprof:24

RUN apt update && apt -y install git maven

RUN mkdir /app && mkdir /sources

RUN git clone https://github.com/petrbouda/jeffrey-testapp.git /sources/jeffrey \
    && mvn clean package -f /sources/jeffrey/pom.xml \
    && cp /sources/jeffrey/server/target/runner.jar /app

RUN rm -rf /sources

ENTRYPOINT ["java", "-jar", "/app/runner.jar"]
