kind: PersistentVolume
apiVersion: v1
metadata:
  name: jeffrey-vol
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/jeffrey-data"
