kind: PersistentVolume
apiVersion: v1
metadata:
  name: jeffrey-vol
  labels:
    type: local
spec:
  storageClassName: shared-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/jeffrey-data"
